### ISSUE TITLE
Amixer unable to find 'master' error

### ISSUE THREAD

**Issue by lewisdav65** [jaromaz/MacintoshPi#11]
When I try to start any emulator (e.g. Mac os9) I get two errors, both saying :-
    Amixer: Unable find simple control 'Master',0
The emulator then does not start-it just shows the command  prompt (although it does play the start-up sound when the error messages appear).
I'm using a Raspberry pi model 3A+
I've also tried  reinstalling the OS (Raspberry Pi OS Lite (Legacy)) and files on the microsd card, but get exactly the same error.
I'm a newbie as far as Linux goes.

If I use the 'amixer' command it returns:-
simple mixer control 'HDMI',0
Capabilities: pvolume pvolume-joined pswitch pswitch -joined
Playback channels: mono
Limits: Playback -10239 -400
Mono: playback 0 [96%] [0.00db] [on]

***UPDATE*** I started from scratch using a different microsd card (an old 8gb card rather than the more recent 32gb I was using earlier) and it works fine. I did the same process for the 8gb card as I did with the other card, so I don't know why this works but the other gave the amixer errors (even when rebuilt twice) 
Anyway, all good now

**Comment by jaromaz** [comment]
It's good to hear that everything is fine.
