### ISSUE TITLE
Attempting to run Commodore results in reboot

### ISSUE THREAD

**Issue by privatedev11** [jaromaz/MacintoshPi#15]
If I run ```mac commodore``` to run the Commodore emulator, it just reboots and makes my screen tiny. Have I screwed something up or is this a genuine bug?

**Comment by jaromaz** [comment]
To handle the Commodore you need to install the BMC64 emulator according to this manual:
https://github.com/jaromaz/MacintoshPi/tree/main/dual-boot

**Comment by privatedev11** [comment]
So sorry, didn't see this. Thanks for the help!
