### ISSUE TITLE
Best way to upgrade/update?

### ISSUE THREAD

**Issue by aptonline** [jaromaz/MacintoshPi#19]
Hi, I have an other version of MacintoshPi installed, what would the steps be to perform an upgrade especially if you have customised images etc?

Many thanks

**Comment by jaromaz** [comment]
Make a copy of your images, reinstall MacintoshPi (preferably on a clean SD card), overwrite the images.

**Comment by aptonline** [comment]
Simple, I did make some additional configurations which I'm assuming I can follow the same backup and restore process after updating the image?

**Comment by jaromaz** [comment]
Yes, of course.
