### ISSUE TITLE
it giving an error : cant download: mac os 7 hdd image

### ISSUE THREAD

**Issue by Qkilov** [jaromaz/MacintoshPi#20]
also cant connect to https://homer-retro.space/appfiles/

**Comment by GaryBrigden** [comment]
Hi. I too am not able to see the app files directory. Seems to be down :(

**Comment by jaromaz** [comment]
It is already working again.

**Comment by Halcyon522** [comment]
This appears to be happening again. When I try to manually check out `https://homer-retro.space/appfiles/`, I just see an image and a link back to `https://homer-retro.space/`. Oddly enough, going to `https://homer-retro.space/appfiles/as/` actually works.
