### ISSUE TITLE
Video issues in Raspi Zero W

### ISSUE THREAD

**Issue by mdev88** [jaromaz/MacintoshPi#24]
Hello, I have successfully installed MacintoshPi in a Raspberry Pi Zero W v1.1 
The build script downloaded and compiled everything without errors, but then I have the following issues:

1. Both Mac OS 7 and 8 have a video issue where the image looks out of sync:

![photo_2023-06-01_10-39-30](https://github.com/jaromaz/MacintoshPi/assets/7395872/caef2d1a-bf03-4dbe-847a-0138eabca1f9)

The whole image moves slowly to the right:

https://github.com/jaromaz/MacintoshPi/assets/7395872/da84fa80-54a2-41ba-a326-925b6e330a81

2. And Mac OS 9 doesn't even start. I just get a couple of seconds of black screen and then back to the prompt, no errors or anything.

Any help would be apreciated. Thanks!

**Comment by mdev88** [comment]
Update: I have used `raspi-config` to set the screen resolution to 640x480 to see if it helped, but no, same issue as before.

**Comment by mdev88** [comment]
I just saw a closed issue regarding this same problem. I'll try that solution and close the issue if it works.

**Comment by mdev88** [comment]
Ok, I have tried all the commands for os7, 8 with basically the same result, only that with lower resolutions the image slides up and to the right instead of only to the right. os9 doesn't even seem to start at all...

**Comment by mdev88** [comment]
Is there anything I can try to debug this issue...?

**Comment by jaromaz** [comment]
I guess it's just that the Raspberry Pi Zero should be removed from the list of supported devices, because MacintoshPi was only tested on the Raspberry Pi Zero 2 W device.

Done: https://github.com/jaromaz/MacintoshPi/commit/5282945d9f7cdd25cf349f443cca1272988a2df4

**Comment by matsondawson** [comment]
I found that running "aconnect -x" before SheepSaver makes os9 work on Zero W.
```
sudo aconnect -x && sudo padsp SheepShaver --config /usr/share/macintoshpi/macos9/macos9.cfg
```
There were a lot of these errors and another forum suggested it.
```
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
```

**Comment by matsondawson** [comment]
Just got OS8 to work one of these things did it:
* Delete ether slirp from the os8 config
* Build and install latest SDL

**Comment by matsondawson** [comment]
Just got OS7 to work, by removing the ether slirp os7 config.
For some reason slirp scrambles the screen.

**Comment by matsondawson** [comment]
Just did a complete reimage and install of mac.
None of what I previously did worked.
But this did:
Create a batch file with this (for some reason sudo is important, without sudo it screws up the screen)
```
#!/bin/sh

sudo BasiliskII --config /usr/share/macintoshpi/macos7/macos7.cfg
```

Now I did install SDL again, but I think you don't need it.
And my ethernet issues were to do with me using a pi install that was installed on a different version pi.
