### ISSUE TITLE
Error - can't download: Mac OS 7 apt packages

### ISSUE THREAD

**Issue by tomasantunes** [jaromaz/MacintoshPi#3]
I followed the instructions and I ended up with a 404 error downloading a couple of packages.

Here are the logs:
```
Err:1 http://raspbian.raspberrypi.org/raspbian buster/main armhf libcups2 armhf 2.2.10-6+deb10u5
Err:2 http://raspbian.raspberrypi.org/raspbian buster/main armhf libxml2-utils armhf 2.9.4+dfsg1-7+deb10u3
```

**Comment by tomasantunes** [comment]
Sorry, this has been solved by updating and rebooting.

**Comment by jaromaz** [comment]
Information about the update and reboot requirement is displayed at the beginning - just after running the script :)
