### ISSUE TITLE
Can't Download Mac OS 9 ROM File

### ISSUE THREAD

**Issue by rainbowmst3000** [jaromaz/MacintoshPi#31]
![PXL_20231110_053957144 PORTRAIT ORIGINAL](https://github.com/jaromaz/MacintoshPi/assets/74487607/cd26542d-dbbe-41f9-8441-265d230396f7)
Hi Sorry for bothering you again but there seems to be an issue with OS 9. The other two work fine, but OS 9 seems to have a problem. I have tried this at a few different times in case the server was down but no luck. Any suggestions? Apprently this was an issue before and has to do with a missing certificate? Thanks.

**Comment by jaromaz** [comment]
For some reason the ROM file is not downloading at your location: https://smb4.s3.us-west-2.amazonaws.com/sheepshaver/apple_roms/newworld86.rom.zip

I checked a while ago and it is downloading correctly.

**Comment by rainbowmst3000** [comment]
![image](https://github.com/jaromaz/MacintoshPi/assets/74487607/2825179c-c818-4a3f-a4e5-f188b53a211e)
The files in the macos9 directory under usr/share/macintoshpi/macos9 were set to have a user of "root." I renamed this directory to macos9old and created a new directory for macos9 and copied over the macos9.cfg file. Then everything worked. Thanks! It's great.
