### ISSUE TITLE
Fail during MacOS 9 install

### ISSUE THREAD

**Issue by brayne** [jaromaz/MacintoshPi#32]
Install fails during MacOS 9 stage, with the following errors:

```
E: Unable to locate package libesd0-dev

Error - can't download: Mac OS 9 apt packages
Check your Internet connection and try again later.
```

My internet connection is fine. Have tried twice with the same result.

**Comment by dj1ch** [comment]
`sudo apt install libesd0* -y` maybe? this will just install any package that has `libesd0` in the name. also make sure you're using the correct image, maybe that package could not be provided in that version of raspberry pi os
