### ISSUE TITLE
Downloads directory not auto created

### ISSUE THREAD

**Issue by aptonline** [jaromaz/MacintoshPi#5]
Not sure if this is something that should be done as part of the setup but as the `Downloads` directory within `/home/pi` is not auto created (as least for me) the `Unix` directory on the Apple desktop is not created.

Manually creating this directory then shows the `Unix` directory on the desktop in each Mac OS.

**Comment by jaromaz** [comment]
The bug has just been fixed in the sources - the fix will appear in the new release soon.
I thought everyone would install the English version of the Raspberry Pi OS :)

**Comment by aptonline** [comment]
Thanks for the update. I did install the English version btw :)
