### ISSUE TITLE
Boot from another .img or .dsk file?

### ISSUE THREAD

**Issue by aptonline** [jaromaz/MacintoshPi#7]
I’ve successfully installed MacOS 7.6 onto a blank image and have been trying to get the MacOS 7 command to boot it by passing the image name but it keeps booting from the default MacOS 7 HDD image and simply mounting the image even if I bless the volume using Startup Disk control panel.

Is this expected behaviour or should it boot? 

It would be really good if you could pass an argument to each Mac OS to boot from a particular install in a future update.

Thanks

**Comment by jaromaz** [comment]
You should replace the main boot disk located in the directory: 
```/usr/share/macintoshpi/macos7/```.

The ```mac os7 file.dsk``` command is used to place additional disks to the default system.

**Comment by aptonline** [comment]
I realise I could do that but it would be useful to pass an argument to override this behaviour and be able to boot to different versions at will.

**Comment by jaromaz** [comment]
You can always create a new Basilisk II configuration file and put it in the directory e.g.: 
```/etc/macintoshpi/myos```

then the ```mac myos``` command will boot your Mac OS 7 image, and the ```mac os7``` command will boot the default Mac OS 7 image.

**Comment by aptonline** [comment]
Worked a treat. Thanks for the tip 👍.
