### ISSUE TITLE
Feature Request: Pass audio over Bluetooth

### ISSUE THREAD

**Issue by aptonline** [jaromaz/MacintoshPi#8]
One use case I have is that I’m running MacintoshPi on a Zero W2 and I sometimes connect it to a monitor that does not have built in speakers and the Zero W2 does not have an AUX port.

A solution in this situation would be to pass audio over Bluetooth using something like PulseAudio (https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/)

**Comment by jaromaz** [comment]
I was not planning any more major changes to the project. But you can always create a pull request :)
