### ISSUE TITLE
raspberry pi4

### ISSUE THREAD

**Issue by Raulking868** [jaromaz/MacintoshPi#9]
how can i make it run on raspberry pi4?

**Comment by jaromaz** [comment]
In this version, it is impossible. I'm waiting for a pull request that will allow the project to run on Raspberry Pi 4 :)

**Comment by Latchkey1998** [comment]
you could run it on the pi 4 if you use the kanji talk fork but it requires the x11 server but on pi 4 it runs mac os 9 at 1920/1080 very nicley
